# Generated by Django 5.1.1 on 2024-10-02 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=10)),
                ('flat_area', models.IntegerField()),
                ('flat_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='meters.house')),
            ],
        ),
    ]
