# Generated by Django 5.1.1 on 2024-10-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wm_inv', models.CharField(max_length=50)),
                ('wm_flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='meters.flat')),
            ],
        ),
    ]
