# Generated by Django 5.1.1 on 2024-10-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_watermeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_value', models.IntegerField()),
                ('mv_month', models.IntegerField()),
                ('mv_meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='values', to='meters.watermeter')),
            ],
        ),
    ]
