# Generated by Django 5.1.1 on 2024-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_alter_tariff_tariff_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_ind',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
        migrations.AddField(
            model_name='house',
            name='house_odn',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
    ]
