# Generated by Django 5.1.1 on 2024-10-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_house_house_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_ind',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_odn',
        ),
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_month', models.IntegerField()),
                ('calc_status', models.CharField(max_length=10)),
                ('calc_odn_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('calc_ind_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('calc_start', models.CharField(max_length=50)),
                ('calc_end', models.CharField(max_length=50)),
                ('calc_progress', models.CharField(max_length=10)),
                ('calc_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='meters.house')),
            ],
        ),
    ]
