# Generated by Django 5.1.1 on 2024-10-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_remove_house_house_ind_remove_house_house_odn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='calc_ind_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='calc_odn_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
