# Generated by Django 5.1.1 on 2024-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0009_alter_calculations_calc_ind_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='calc_progress',
        ),
        migrations.AddField(
            model_name='calculations',
            name='calc_errors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='calculations',
            name='calc_warnings',
            field=models.TextField(default=''),
        ),
    ]
