# Generated by Django 5.1.1 on 2024-10-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0010_remove_calculations_calc_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
