# Generated by Django 4.2.16 on 2024-10-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0011_alter_flat_flat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_status',
        ),
    ]
