# Generated by Django 4.2.16 on 2024-10-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0012_remove_house_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('flat_number', 'flat_house')},
        ),
    ]
